# Generated by Django 4.1.2 on 2022-10-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_username", models.CharField(max_length=50)),
                ("backend", models.BooleanField(default=True)),
                ("age", models.PositiveIntegerField()),
                ("bio", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "Abouts",
            },
        ),
    ]
