# Generated by Django 4.1.2 on 2022-10-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
    ]
